# Generated by Django 4.0.3 on 2022-04-12 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mizukis_cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beans',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
